root = {
    "name": "1f2f269bbf00",
    "cluster_name": "docker-cluster",
    "cluster_uuid": "rsdKq8NWTc68fWYleQGyDw",
    "version": {
        "number": "7.4.2",
        "build_flavor": "default",
        "build_type": "docker",
        "build_hash": "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
        "build_date": "2019-10-28T20:40:44.881551Z",
        "build_snapshot": False,
        "lucene_version": "8.2.0",
        "minimum_wire_compatibility_version": "6.8.0",
        "minimum_index_compatibility_version": "6.0.0-beta1"
    },
    "tagline": "You Know, for Search"
}

xpack = {"build": {"hash": "2f90bbf7b93631e52bafb59b3b049cb44ec25e96", "date": "2019-10-28T20:40:44.898709Z"},
        "license": {"uid": "1a10d63d-af33-4475-8d43-1311e573fd14", "type": "basic", "mode": "basic",
                    "status": "active"}, "features": {"analytics": {"available": True, "enabled": True},
                                                      "ccr": {"available": False, "enabled": True},
                                                      "data_frame": {"available": True, "enabled": True},
                                                      "flattened": {"available": True, "enabled": True},
                                                      "frozen_indices": {"available": True, "enabled": True},
                                                      "graph": {"available": False, "enabled": True},
                                                      "ilm": {"available": True, "enabled": True},
                                                      "logstash": {"available": False, "enabled": True},
                                                      "ml": {"available": False, "enabled": True},
                                                      "monitoring": {"available": True, "enabled": True},
                                                      "rollup": {"available": True, "enabled": True},
                                                      "security": {"available": True, "enabled": False},
                                                      "spatial": {"available": True, "enabled": True},
                                                      "sql": {"available": True, "enabled": True},
                                                      "vectors": {"available": True, "enabled": True},
                                                      "voting_only": {"available": True, "enabled": True},
                                                      "watcher": {"available": False, "enabled": True}}}

policy = {"error": {"root_cause": [
    {"type": "resource_not_found_exception", "reason": "Lifecycle policy not found: winlogbeat-7.4.2"}],
    "type": "resource_not_found_exception",
    "reason": "Lifecycle policy not found: winlogbeat-7.4.2"}, "status": 404}

ack = {"acknowledged": True}

bulk = {"took": 209, "errors": False, "items":
    [{"index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                "_type": "_doc", "_id": "XTL8X24By5cH59AY7zwP",
                "_version": 1, "result": "created",
                "_shards": {"total": 2, "successful": 1,
                            "failed": 0}, "_seq_no": 0,
                "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "XjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 1,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "XzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 2,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "YDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 3,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "YTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 4,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "YjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 5,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "YzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 6,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ZDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 7,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ZTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 8,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ZjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 9,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ZzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 10,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "aDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 11,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "aTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 12,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ajL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 13,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "azL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 14,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "bDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 15,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "bTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 16,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "bjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 17,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "bzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 18,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "cDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 19,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "cTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 20,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "cjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 21,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "czL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 22,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "dDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 23,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "dTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 24,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "djL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 25,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "dzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 26,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "eDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 27,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "eTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 28,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ejL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 29,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ezL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 30,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "fDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 31,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "fTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 32,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "fjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 33,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "fzL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 34,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "gDL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 35,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "gTL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 36,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "gjL8X24By5cH59AY7zwP",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 37,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "gzL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 38,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "hDL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 39,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "hTL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 40,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "hjL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 41,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "hzL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 42,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "iDL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 43,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "iTL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 44,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "ijL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 45,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "izL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 46,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "jDL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 47,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "jTL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 48,
                   "_primary_term": 1, "status": 201}}, {
         "index": {"_index": "winlogbeat-7.4.2-2019.11.12-000001",
                   "_type": "_doc", "_id": "jjL8X24By5cH59AY7zwQ",
                   "_version": 1, "result": "created",
                   "_shards": {"total": 2, "successful": 1,
                               "failed": 0}, "_seq_no": 49,
                   "_primary_term": 1, "status": 201}}]}

now = {"aliases": {"winlogbeat-7.4.2": {"is_write_index": True}}}